# Generated by Django 3.1.3 on 2022-05-08 15:56

import authentication.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=30, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, unique=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=True, verbose_name='staff')),
                ('email_verified', models.BooleanField(default=True, verbose_name='email verified')),
                ('action', models.CharField(choices=[('1', 'No preference'), ('2', 'Own a room'), ('3', 'Need a room')], default='1', max_length=14, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'username',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', authentication.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_room_gender', models.CharField(choices=[('1', 'Male'), ('2', 'Strictly Female'), ('3', 'Any')], max_length=14, null=True)),
                ('pets_allowed', models.CharField(choices=[('1', 'Pets are not allowed'), ('2', 'Sure, you can bring yours')], max_length=14, null=True)),
                ('smoking_allowed', models.CharField(choices=[('1', 'Not allowed'), ('2', 'Allowed')], max_length=14, null=True)),
                ('pref_age_range', models.CharField(choices=[('1', '< 18'), ('2', '18 - 25'), ('3', '> 25')], max_length=14, null=True)),
                ('pref_religion', models.CharField(choices=[('1', 'Christian'), ('2', 'Moslem'), ('3', 'I am ok with any..')], max_length=14, null=True)),
                ('room_clean', models.CharField(choices=[('1', 'We hire cleaners'), ('2', 'We do the cleaning ourselves')], max_length=14, null=True)),
                ('room_noise', models.CharField(choices=[('1', 'If it is not really loud, No problem'), ('2', 'If anyone needs silence, that is the law of the house'), ('3', 'Frequent quiet time')], max_length=14, null=True)),
                ('out_of_towners', models.CharField(choices=[('1', 'Not allowed'), ('2', 'Allowed')], max_length=14, null=True)),
                ('family_visits', models.CharField(choices=[('1', 'Not allowed'), ('2', 'Allowed')], max_length=14, null=True)),
                ('course_of_interest', models.TextField(blank=True, max_length=222)),
                ('bio', models.CharField(blank=True, max_length=14)),
                ('phone_no', models.CharField(blank=True, max_length=14)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to specify', 'Prefer not to specify')], max_length=225, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
