# Generated by Django 3.1.3 on 2022-05-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course_of_interest',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
