# Generated by Django 3.1.3 on 2022-05-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220509_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course_of_interest',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
