# Generated by Django 3.1.3 on 2022-05-16 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20220516_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.school'),
        ),
    ]
