# Generated by Django 3.1.3 on 2022-05-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20220517_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='action',
            field=models.CharField(choices=[('1', 'No preference'), ('2', 'Own a room/Need room mate'), ('3', 'Need a room/Need room mate')], default='1', max_length=14, null=True),
        ),
    ]
