# Generated by Django 3.1.3 on 2022-05-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20220523_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='user',
            name='course_of_interest',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='family_visits',
            field=models.CharField(choices=[('1', 'Not allowed'), ('2', 'Allowed')], max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='out_of_towners',
            field=models.CharField(choices=[('1', 'Not allowed'), ('2', 'Allowed')], max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pets_allowed',
            field=models.CharField(choices=[('1', 'Pets are not allowed'), ('2', 'Sure, you can bring yours')], max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='user',
            name='pref_age_range',
            field=models.CharField(choices=[('1', '< 18'), ('2', '18 - 25'), ('3', '> 25')], max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pref_religion',
            field=models.CharField(choices=[('1', 'Christian'), ('2', 'Moslem'), ('3', 'I am ok with any..')], max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pref_room_gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Strictly Female'), ('3', 'Any')], max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='room_clean',
            field=models.CharField(choices=[('1', 'We hire cleaners'), ('2', 'We do the cleaning ourselves')], max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='room_noise',
            field=models.CharField(choices=[('1', 'If it is not really loud, No problem'), ('2', 'If anyone needs silence, that is the law of the house'), ('3', 'Frequent quiet time')], max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='smoking_allowed',
            field=models.CharField(choices=[('1', 'Not allowed'), ('2', 'Allowed')], max_length=14, null=True),
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
