# Generated by Django 3.1.3 on 2022-05-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20220524_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='user/'),
        ),
    ]
