# Generated by Django 3.1.3 on 2022-06-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='assets/image/avatar.png', null=True, upload_to='user/'),
        ),
    ]
