# Generated by Django 3.1.3 on 2022-06-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20220607_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user/avatar.png', null=True, upload_to='user/'),
        ),
    ]
