# Generated by Django 3.1.3 on 2022-06-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20220608_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='he.png', null=True, upload_to='users/'),
        ),
    ]
