# Generated by Django 3.1.3 on 2022-05-08 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('type', models.CharField(choices=[('1', 'A Room'), ('2', 'A Room Selfcon'), ('3', 'Two Bedroom')], max_length=225, null=True)),
                ('address', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('rent_range', models.CharField(choices=[('1', '10k -50k'), ('2', '50k -100k'), ('3', '> 100k')], max_length=14, null=True)),
                ('bills', models.CharField(choices=[('1', 'Split bills evenly'), ('2', 'Negotiatory')], max_length=14, null=True)),
                ('room_composition', models.CharField(choices=[('1', 'One person'), ('2', 'Two'), ('3', 'More Than Two')], max_length=14, null=True)),
                ('stay_duration', models.CharField(choices=[('1', 'One Semester'), ('2', 'One Session'), ('3', 'ShortTerm'), ('4', 'LongTerm'), ('5', 'Negotiatory')], max_length=14, null=True)),
                ('home_furnishing', models.CharField(choices=[('1', 'Completly furnished'), ('2', 'Partially'), ('3', 'Nothing dey for this room')], max_length=14, null=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_room', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iroomie.school')),
            ],
        ),
    ]
