# Generated by Django 3.1.3 on 2022-06-03 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iroomie', '0002_auto_20220509_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.AddField(
            model_name='room',
            name='room_display_image_four',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='roon/'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_display_image_one',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='roon/'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_display_image_three',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='roon/'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_display_image_two',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='roon/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='home_furnishing',
            field=models.CharField(choices=[('1', 'Completely furnished'), ('2', 'Partially'), ('3', 'Nothing dey for this room')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('A Room', 'A Room'), ('A Room Selfcon', 'A Room Selfcon'), ('Two Bedroom', 'Two Bedroom')], max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('experience', models.TextField(max_length=225)),
                ('date', models.DateTimeField(auto_now=True)),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='iroomie.room')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='additional_amenity',
            field=models.ManyToManyField(to='iroomie.Amenity'),
        ),
    ]
