# Generated by Django 3.1.3 on 2022-06-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iroomie', '0005_auto_20220603_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='display_video',
            field=models.FileField(blank=True, default='default-avatar.mp4', null=True, upload_to='room_videos/'),
        ),
    ]
