# Generated by Django 3.1.3 on 2022-06-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iroomie', '0006_room_display_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='display_video',
            field=models.FileField(default='default-avatar.mp4', null=True, upload_to='room_videos/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_display_image_four',
            field=models.ImageField(default='default-avatar.png', null=True, upload_to='roon/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_display_image_one',
            field=models.ImageField(default='default-avatar.png', null=True, upload_to='roon/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_display_image_three',
            field=models.ImageField(default='default-avatar.png', null=True, upload_to='roon/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_display_image_two',
            field=models.ImageField(default='default-avatar.png', null=True, upload_to='roon/'),
        ),
    ]
