# Generated by Django 3.1.3 on 2022-06-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iroomie', '0007_auto_20220606_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='display_video',
            field=models.FileField(null=True, upload_to='room_videos/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_display_image_four',
            field=models.ImageField(null=True, upload_to='room/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_display_image_one',
            field=models.ImageField(null=True, upload_to='room/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_display_image_three',
            field=models.ImageField(null=True, upload_to='room/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_display_image_two',
            field=models.ImageField(null=True, upload_to='room/'),
        ),
    ]
