# Generated by Django 3.1.3 on 2022-06-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iroomie', '0010_auto_20220614_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='display_video',
            field=models.FileField(blank=True, null=True, upload_to='room_videos/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_display_image_four',
            field=models.ImageField(blank=True, null=True, upload_to='room/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_display_image_three',
            field=models.ImageField(blank=True, null=True, upload_to='room/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_display_image_two',
            field=models.ImageField(blank=True, null=True, upload_to='room/'),
        ),
    ]
